package com.faker.llm.domain

/**
 * Provider-agnostic streaming event. The engine emits a `Flow<AbstractStreamEvent>`;
 * each adapter maps these into its native SSE shape:
 *
 * - OpenAI: `data: {choices: [{delta: {...}}]}` → `data: [DONE]`
 * - Anthropic: `event: message_start` → `event: content_block_*` → `event: message_stop`
 *
 * Runtime-only — never serialized to disk or JSON.
 */
sealed interface AbstractStreamEvent {

    /** Logical start of the response; adapters emit `message_start` / `role: assistant` here. */
    data object StreamStart : AbstractStreamEvent

    data class TextChunk(val delta: String) : AbstractStreamEvent
    data class ThinkingChunk(val delta: String) : AbstractStreamEvent

    /** Begin a tool call; [callId] is generated by the engine, not the pool. */
    data class ToolCallStart(val toolName: String, val callId: String) : AbstractStreamEvent
    data class ToolCallArgsChunk(val delta: String) : AbstractStreamEvent
    data class ToolCallEnd(val callId: String) : AbstractStreamEvent

    /** Mid-stream failure injection. Adapters honor [MidStreamErrorKind] semantics on receipt. */
    data class StreamError(val kind: MidStreamErrorKind, val body: ErrorBody) : AbstractStreamEvent

    /** Successful terminator. Never emitted after [StreamError]. */
    data class StreamEnd(val finishReason: FinishReason, val usage: UsageStub) : AbstractStreamEvent
}
